server:
  port: 8080

spring:
  application:
    name: cubox
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/admin
    username: root
    password: Dongcci92!!

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show_sql: true
    format_sql: true
    time_zone: Asia/Seoul

logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
    org.springframework.web: DEBUG
