server:
  port: 8080

spring:
  application:
    name: cubox
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cubox
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        time_zone: Asia/Seoul
        ddl-auto: update
        database-platform: org.hibernate.dialect.MySQL8Dialect